baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Cognify431"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Cognify431"
  description: "We unlock the connections of your creativity through artificial intelligence."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "431 MSDS Drive, Northwestern Campus, Evanston IL 60208"

  contact:
    - "jmwest AT gmail.com"
    - "555.555.5555"

  copyright: "This Is Satire and Was Built for a Northwestern Data Science Class"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "What is Going On"
      url: "/real"
      weight: 2

    - name: "Our team"
      url: "/bios"
      weight: 3

    - name: "Pricing"
      url: "/pricing"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/real"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "How we work"
      url: "/real"
      weight: 2

    - name: "Our team"
      url: "/bios"
      weight: 3

    - name: "Pricing"
      url: "/pricing"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
